import type { ExamQuestion } from '@learncourse/framework/types';

export const S6_SIM_QUESTIONS: ExamQuestion[] = [
  {
    id: "sim-s6-1",
    moduleId: "s6",
    year: "模拟题",
    position: "自编",
    points: 12,
    questionText: "<p><strong>题目：</strong>已知以下前提（论域为所有人）：</p><p>(1) 如果任何人通过了考试且交了论文，则他获得学分：∀x (Passed(x) ∧ Submitted(x) → Credit(x))</p><p>(2) 所有学生都通过了考试：∀x (Student(x) → Passed(x))</p><p>(3) 有些学生交了论文：∃x (Student(x) ∧ Submitted(x))</p><p>(4) Alice 是一名学生：Student(Alice)</p><p><strong>用归结原理证明：</strong>∃x (Student(x) ∧ Credit(x))（有学生获得了学分）。要求写出完整的转换过程（FOL → CNF → Skolem 化 → 归结步骤）。</p>",
    answerHtml: "<p><strong>第 1 步：将前提和结论否定转为 FOL 公式</strong></p><p><strong>前提 CNF 化：</strong></p><p>前提 (1) ∀x (Passed(x) ∧ Submitted(x) → Credit(x))<br>= ∀x (¬(Passed(x) ∧ Submitted(x)) ∨ Credit(x)) &nbsp;&nbsp;[消去 →]<br>= ∀x (¬Passed(x) ∨ ¬Submitted(x) ∨ Credit(x)) &nbsp;&nbsp;[De Morgan]<br><strong>子句 C1: {¬Passed(x), ¬Submitted(x), Credit(x)}</strong></p><p>前提 (2) ∀x (Student(x) → Passed(x))<br>= ∀x (¬Student(x) ∨ Passed(x)) &nbsp;&nbsp;[消去 →]<br><strong>子句 C2: {¬Student(x), Passed(x)}</strong></p><p>前提 (3) ∃x (Student(x) ∧ Submitted(x))<br>→ Skolem 化：消除 ∃，引入 Skolem 常量 C<br>= Student(C) ∧ Submitted(C)<br>拆为两个子句：<br><strong>子句 C3: {Student(C)}<br>子句 C4: {Submitted(C)}</strong></p><p>前提 (4) <strong>子句 C5: {Student(Alice)}</strong>（已是 CNF）</p><p><strong>结论否定：</strong>¬∃x (Student(x) ∧ Credit(x))<br>= ∀x ¬(Student(x) ∧ Credit(x)) &nbsp;&nbsp;[量词否定]<br>= ∀x (¬Student(x) ∨ ¬Credit(x)) &nbsp;&nbsp;[De Morgan]<br><strong>子句 C6: {¬Student(x), ¬Credit(x)}</strong></p><p><strong>第 2 步：归结推导</strong></p><table><tbody><tr><th>步骤</th><th>父子句</th><th>归结结果</th><th>替换</th></tr><tr><td>7</td><td>C2 + C3</td><td>¬Student(C) ∨ Passed(C) ⊗ Student(C) → <strong>{Passed(C)}</strong></td><td>{x/C}</td></tr><tr><td>8</td><td>C1 + C4</td><td>¬Passed(C) ∨ ¬Submitted(C) ∨ Credit(C) ⊗ Submitted(C) → <strong>{¬Passed(C), Credit(C)}</strong></td><td>{x/C}</td></tr><tr><td>9</td><td>步骤 7 + 步骤 8</td><td>Passed(C) ⊗ (¬Passed(C) ∨ Credit(C)) → <strong>{Credit(C)}</strong></td><td>—</td></tr><tr><td>10</td><td>C3 + C6</td><td>Student(C) ⊗ (¬Student(C) ∨ ¬Credit(C)) → <strong>{¬Credit(C)}</strong></td><td>{x/C}</td></tr><tr><td>11</td><td>步骤 9 + 步骤 10</td><td>Credit(C) ⊗ ¬Credit(C) → <strong>□（空子句）</strong></td><td>—</td></tr></tbody></table><p><strong>结论：</strong>从 KB ∪ {¬Goal} 推出空子句 □ → 矛盾 → ¬Goal 与 KB 冲突 → <strong>Goal 必然为真，得证 ∃x (Student(x) ∧ Credit(x))。</strong></p><hr /><p><strong>评分要点：</strong></p><ul><li>每个前提正确转为 CNF 子句（各 1 分，共 4 分）——消去 → 和 De Morgan 步骤必须写出</li><li>前提 (3) 的 Skolem 化正确使用常量 C（1 分）——此处 ∃x 在最外层，没有外围 ∀ 量词，应用 Skolem 常量而非函数</li><li>结论否定 ¬Goal 正确转为 CNF（1 分）——量词否定 + De Morgan 两步都不能漏</li><li>归结步骤每步标注父子句、替换、结果（4 分）——替换（unification）是 FOL 归结区别于命题逻辑的关键</li><li>推出口且正确解释其含义（2 分）——□ = 矛盾 = 假设 ¬Goal 不成立 ≠ 「目标为假」</li></ul>"
  },
  {
    id: "sim-s6-2",
    moduleId: "s6",
    year: "模拟题",
    position: "自编",
    points: 10,
    questionText: "<p><strong>题目：</strong>用自然演绎法证明以下推理。每一步必须标注推理规则。</p><p><strong>前提：</strong></p><p>(1) ∀x (Dog(x) → HasTail(x))</p><p>(2) ∃x (Dog(x) ∧ Brown(x))</p><p><strong>结论：</strong>∃x (HasTail(x) ∧ Brown(x))</p>",
    answerHtml: "<p><strong>证明（自然演绎，9 步）：</strong></p><table><tbody><tr><th>步骤</th><th>公式</th><th>推理规则</th><th>依赖</th></tr><tr><td>1</td><td>∃x (Dog(x) ∧ Brown(x))</td><td>前提 (2)</td><td>—</td></tr><tr><td>2</td><td>Dog(a) ∧ Brown(a)</td><td>∃-elim（存在量词消去）</td><td>步骤 1</td></tr><tr><td>3</td><td>Dog(a)</td><td>∧-elim（合取消去，取左边）</td><td>步骤 2</td></tr><tr><td>4</td><td>Brown(a)</td><td>∧-elim（合取消去，取右边）</td><td>步骤 2</td></tr><tr><td>5</td><td>∀x (Dog(x) → HasTail(x))</td><td>前提 (1)</td><td>—</td></tr><tr><td>6</td><td>Dog(a) → HasTail(a)</td><td>∀-elim（全称量词消去）</td><td>步骤 5，代入 a</td></tr><tr><td>7</td><td>HasTail(a)</td><td>→-elim / Modus Ponens</td><td>步骤 3, 6</td></tr><tr><td>8</td><td>HasTail(a) ∧ Brown(a)</td><td>∧-intro（合取引入）</td><td>步骤 7, 4</td></tr><tr><td>9</td><td>∃x (HasTail(x) ∧ Brown(x))</td><td>∃-intro（存在量词引入）</td><td>步骤 8 ∎</td></tr></tbody></table><p><strong>关键规则说明：</strong></p><ul><li><strong>∃-elim（步骤 2）：</strong>从 ∃x P(x) 引入临时常量 a 代换 x，将 P(a) 作为临时假设。a 必须是全新的常量（未在前提或结论中出现过），且不能在最终结论中残留。</li><li><strong>∀-elim（步骤 6）：</strong>从 ∀x P(x) 将 x 替换为任意项（此处为常量 a），得到 P(a)。这是 FOL 中最常用的规则——把「对所有成立」的特化为「对 a 成立」。</li><li><strong>∃-intro（步骤 9）：</strong>从 P(a) 推出 ∃x P(x)——只要存在一个实例 a 满足性质，就可以引入存在量词。注意这里引入的存在变量是 x，与常量 a 不同名。</li></ul><p><strong>本题考点：</strong>自然演绎中 ∃-elim + ∀-elim + ∃-intro 的接力使用——这是 FOL 混合量词证明的标准套路。先消去存在量词引入临时常量 → 用全称量词消去对常量实例化 → 推导出结果 → 再用存在量词引入封装回去。这条链在考试中反复出现。</p><hr /><p><strong>评分要点：</strong></p><ul><li>∃-elim 正确引入临时常量 a，未使用已有常量（2 分）</li><li>∧-elim 拆解合取，两个方向各 1 分（2 分）</li><li>∀-elim 代入正确（1 分）</li><li>→-elim / Modus Ponens 使用正确（1 分）</li><li>∧-intro 和 ∃-intro 各 1 分（2 分）</li><li>每步推理规则标注正确（2 分）——错误标注或漏标注每步扣 0.5 分</li></ul>"
  },
  {
    id: "sim-s6-3",
    moduleId: "s6",
    year: "模拟题",
    position: "自编",
    points: 8,
    questionText: "<p><strong>题目：</strong>在 Wumpus 世界中，智能体从 [1,1] 出发，已知 [1,1] 没有陷阱（¬P_11）也没有 Wumpus（¬W_11）。智能体移动到 [2,1]，感知到微风（Breeze, B_21 = True）但没有恶臭（Stench, S_21 = False）。</p><p><strong>知识库 KB 包含：</strong></p><p>B_21 ↔ (P_11 ∨ P_22 ∨ P_31)</p><p>S_21 ↔ (W_11 ∨ W_22 ∨ W_31)</p><p><strong>(a)</strong> 根据感知和 KB，逐一推导 [2,2] 和 [3,1] 中陷阱（Pit）和 Wumpus 的情况。写出推理步骤和所用规则。（5 分）</p><p><strong>(b)</strong> 说明智能体下一步的合理行动及推理依据。（3 分）</p>",
    answerHtml: "<p><strong>(a) 推理过程（5 分）</strong></p><p><strong>Wumpus 分析：</strong></p><p>S_21 ↔ (W_11 ∨ W_22 ∨ W_31) 是双向蕴涵，利用 ↔-elim 分解为两个方向：</p><p>(i) S_21 → (W_11 ∨ W_22 ∨ W_31) &nbsp;&nbsp;&nbsp;(ii) (W_11 ∨ W_22 ∨ W_31) → S_21</p><p>已知 S_21 = False（没有恶臭），对方向 (ii) 使用 <strong>Modus Tollens</strong>：</p><p>¬S_21 ⊢ ¬(W_11 ∨ W_22 ∨ W_31)</p><p>¬(W_11 ∨ W_22 ∨ W_31) = <strong>¬W_11 ∧ ¬W_22 ∧ ¬W_31</strong>（De Morgan）</p><p>已知 ¬W_11（前提），确认 <strong>¬W_22 且 ¬W_31</strong>——[2,2] 和 [3,1] 均无 Wumpus，安全。</p><div class=\"callout callout--tip\"><strong>关键：</strong>这是 ↔（当且仅当）的力量——只有 ↔ 才能从「没有感知」推出「没有原因」。如果 KB 只用单向 →（如有 Wumpus 则有恶臭），就无法从 ¬S_21 推出任何结论。</div><p><strong>陷阱分析：</strong></p><p>B_21 ↔ (P_11 ∨ P_22 ∨ P_31) 同样分解：(iii) B_21 → (P_11 ∨ P_22 ∨ P_31)</p><p>已知 B_21 = True（有微风），对方向 (iii) 使用 <strong>Modus Ponens</strong>：</p><p>B_21, B_21 → (P_11 ∨ P_22 ∨ P_31) ⊢ <strong>P_11 ∨ P_22 ∨ P_31</strong></p><p>已知 ¬P_11（前提），使用 <strong>析取三段论（Disjunctive Syllogism）</strong>：</p><p>P_11 ∨ P_22 ∨ P_31, ¬P_11 ⊢ <strong>P_22 ∨ P_31</strong></p><p><strong>结论：</strong>[2,2] 或 [3,1]（或两者）中存在陷阱，但无法唯一确定是哪一个——需要进一步探索。</p><p><strong>(b) 合理行动（3 分）</strong></p><p>当前位于 [2,1]。已知安全的格子：</p><ul><li>[1,1] —— 确定安全（起始位置已验证）</li><li>[2,1] —— 确定安全（当前位置，正在站）</li><li>[2,2] —— 确定无 Wumpus，但有 50% 概率有陷阱</li><li>[3,1] —— 确定无 Wumpus，但有 50% 概率有陷阱</li><li>[1,2] —— 尚未探索，状态未知</li></ul><p><strong>推荐策略：先回 [1,1]，再探 [1,2]。</strong></p><p>推理依据：</p><ul><li>直接进入 [2,2] 或 [3,1] 有 50% 死亡风险——信息不足以判断哪个有陷阱，贸然进入是赌博。</li><li>回到 [1,1]（安全），然后进入 [1,2] 探索新方向。在 [1,2] 的感知结果（是否有微风/恶臭）将提供新信息——可能帮助确定 [2,2] 是否有陷阱（如果 [1,2] 感知到微风且排除 [1,1] 和已访问格子，则线索收窄）。</li><li>如果 Wumpus 世界只允许前进不能后退，则选择风险较小的一侧（[2,2] 或 [3,1]），但应先检查是否有其他安全信息（如通过消去法确定唯一陷阱位置）。</li></ul><p><strong>备选激进策略：</strong>如果陷阱只有一个（常见设定），则 P_22 ∨ P_31 意味着恰好一个为真。Agent 可以选择探 [3,1]——如果幸存，则 [2,2] 必然有陷阱；如果死亡，则 [3,1] 就是陷阱。这种「以身试险」策略在有生命数或可重置的场景中合理。</p><hr /><p><strong>评分要点：</strong></p><ul><li>(a) Wumpus 推理：正确使用 Modus Tollens（↔ 方向识别准确）+ De Morgan 展开（2 分）</li><li>(a) 陷阱推理：正确使用 Modus Ponens + 析取三段论得出结论 P_22 ∨ P_31（2 分）</li><li>(a) 明确指出无法唯一确定哪个格子有陷阱（1 分）——这是区分「会推理」和「背答案」的关键</li><li>(b) 合理行动建议且给出逻辑依据（2 分）——不能只说「走那边」，要解释为什么</li><li>(b) 提到可以通过 [1,2] 的感知收窄对 [2,2] 的推理（1 分）——体现信息获取的递归思维</li></ul>"
  }
];