import type { ExamQuestion } from '@learncourse/framework/types';

export const S2_SIM_QUESTIONS: ExamQuestion[] = [
  {
    id: "sim-s2-1",
    moduleId: "s2",
    year: "模拟题",
    position: "自编",
    points: 12,
    questionText: "<p><strong>题型：计算题</strong> | <strong>参考分值：12分</strong></p><p><strong>题目：</strong>给定以下搜索图，S 为起始节点，G 为目标节点。边上标注的数字为路径代价。注意：此图包含环（A 和 B 之间双向可达），需要使用 explored 集合避免重复扩展。</p><pre>        S\n       / \\\n    (3)   (2)\n     /       \\\n    A -------- B\n    |  (2)     |\n    |           |\n   (1)         (5)\n    |           |\n    C ----------+\n    |  (3)\n   (4)\n    |\n    G</pre><p>完整边列表：S→A(3), S→B(2), A↔B(2), A→C(1), B→C(5), C→G(4)。</p><p>(1) 执行<strong>一致代价搜索（Uniform Cost Search, UCS）</strong>，写出每一步所弹出（pop）的节点、扩展后 frontier 中所有节点及其 g 值，并标注哪些节点被加入 explored 集合（8分）</p><p>(2) 指出最终找到的路径及其代价，并简述 UCS 为什么能保证这条路径是最优的（4分）</p>",
    answerHtml: "<h4>(1) UCS 逐步执行（8分）</h4><p><strong>第1步：</strong>Pop S（frontier 中唯一元素）。S 进入 explored。扩展 S → A(g=3), B(g=2)。Frontier: {A(3), B(2)}。</p><p><strong>第2步：</strong>Pop B（g=2 最小）。B 进入 explored。扩展 B → A(2+2=4), C(2+5=7)。A 已在 frontier 中(g=3)，新路径 g=4 > 3，不更新。Frontier: {A(3), C(7)}。</p><p><strong>第3步：</strong>Pop A（g=3 最小）。A 进入 explored。扩展 A → B(3+2=5), C(3+1=4)。B 已在 explored 中，跳过。C 已在 frontier 中(g=7)，新路径 g=4 < 7，更新 C 为 g=4。Frontier: {C(4)}。</p><p><strong>第4步：</strong>Pop C（g=4 最小）。C 进入 explored。扩展 C → G(4+4=8)。Frontier: {G(8)}。</p><p><strong>第5步：</strong>Pop G（g=8 唯一）。G 是目标节点，停止。最终路径：S → A → C → G，代价 = 3 + 1 + 4 = <strong>8</strong>。</p><table><tbody><tr><th>步骤</th><th>弹出</th><th>Frontier（节点+g值）</th><th>Explored</th></tr><tr><td>1</td><td>S</td><td>{A(3), B(2)}</td><td>{S}</td></tr><tr><td>2</td><td>B</td><td>{A(3), C(7)}</td><td>{S, B}</td></tr><tr><td>3</td><td>A</td><td>{C(4)}</td><td>{S, B, A}</td></tr><tr><td>4</td><td>C</td><td>{G(8)}</td><td>{S, B, A, C}</td></tr><tr><td>5</td><td>G</td><td>到达目标</td><td>—</td></tr></tbody></table><h4>(2) 路径与最优性（4分）</h4><p><strong>找到路径：</strong>S → A → C → G，代价 = 3 + 1 + 4 = <strong>8</strong>。</p><p><strong>其他路径对比（验证最优性）：</strong>S→B→C→G = 2+5+4=11；S→A→B→C→G = 3+2+5+4=14；S→B→A→C→G = 2+2+1+4=9。最优路径代价为 8，UCS 正确找到了它。</p><p><strong>UCS 最优性原理：</strong>UCS 总是从 frontier 中弹出 g 值最小的节点。当目标节点 G 第一次被弹出时（而非第一次被生成），它的 g 值一定是所有能到达 G 的路径中最小的——因为 (1) UCS 按 g 升序弹出，(2) 边代价非负，(3) 任何尚未探索的路径经过尚未弹出的节点时，其总代价一定 ≥ 该当前节点的 g（边代价非负保证）。这个性质保证了 UCS 找到的解一定是最优解。</p><hr /><p><strong>评分要点：</strong></p><ul><li>frontier 每步完整列出（含 g 值）→ 4分</li><li>正确处理重复路径更新（B→A 不更新 A，A→C 更新 C 的 g 值）→ 2分</li><li>正确处理 explored（B 在 explored 后从 A 的扩展中跳过）→ 2分</li><li>最终路径和代价正确 + 最优性原理解释正确 → 4分</li></ul>"
  },
  {
    id: "sim-s2-2",
    moduleId: "s2",
    year: "模拟题",
    position: "自编",
    points: 15,
    questionText: "<p><strong>题型：计算+分析题</strong> | <strong>参考分值：15分</strong></p><p><strong>题目：</strong>给定以下搜索图，S 是起始节点，G 是目标节点。边上标注的数字为路径代价，节点旁括号内为启发式函数值 h(n)。</p><pre>           S(h=9)\n          /      \\\n       (2)        (3)\n        /            \\\n     A(h=7)        B(h=4)\n     /    \\         /    \\\n   (1)   (6)     (1)    (4)\n   /        \\     /        \\\nC(h=3)   D(h=5) E(h=2)   F(h=1)\n   |                 |       |\n  (5)               (4)     (2)\n   |                 |       |\n   +-------+---------+-------+\n           |\n          G(h=0)</pre><p>完整边列表：S→A(2), S→B(3), A→C(1), A→D(6), B→E(1), B→F(4), C→G(5), E→G(4), F→G(2)。节点均为唯一（无重名）。</p><p>(1) 执行<strong>贪心最佳优先搜索（Greedy BFS）</strong>，写出每一步弹出节点、frontier 中所有节点及其 h 值，以及最终找到的路径及其代价（5分）</p><p>(2) 执行 <strong>A* 搜索</strong>，写出每一步弹出节点、frontier 中所有节点及其 g/h/f 值，以及最终找到的路径及其代价（7分）</p><p>(3) 对比两种算法的结果，解释为什么 A* 找到了更优（或相同）的路径——结合本例具体数据说明 f=g+h 的意义（3分）</p>",
    answerHtml: "<h4>(1) 贪心最佳优先搜索 Greedy BFS（5分）</h4><table><tbody><tr><th>步骤</th><th>弹出</th><th>扩展后的 Frontier（节点+h）</th><th>选中理由</th></tr><tr><td>1</td><td>S</td><td>{A(h=7), B(h=4)}</td><td>S 初始唯一</td></tr><tr><td>2</td><td><strong>B</strong></td><td>{A(h=7), E(h=2), F(h=1)}</td><td>h(B)=4 最小</td></tr><tr><td>3</td><td><strong>F</strong></td><td>{A(h=7), E(h=2), G(h=0)}</td><td>h(F)=1 最小</td></tr><tr><td>4</td><td><strong>G</strong></td><td>到达目标，停止</td><td>h(G)=0 最小</td></tr></tbody></table><p><strong>节点访问顺序：</strong>S → B → F → G</p><p><strong>找到路径：</strong>S → B → F → G，路径代价 = 3 + 4 + 2 = <strong>9</strong></p><h4>(2) A* 搜索（7分）</h4><table><tbody><tr><th>步骤</th><th>弹出</th><th>扩展后的 Frontier（节点+g/h/f）</th><th>选中理由</th></tr><tr><td>1</td><td>S</td><td>{A(g=2,h=7,f=9), B(g=3,h=4,f=7)}</td><td>S 初始唯一</td></tr><tr><td>2</td><td><strong>B</strong></td><td>{A(2,7,9), E(g=4,h=2,f=6), F(g=7,h=1,f=8)}</td><td>f(B)=7 最小</td></tr><tr><td>3</td><td><strong>E</strong></td><td>{A(2,7,9), F(7,1,8), G(g=8,h=0,f=8)}</td><td>f(E)=6 最小</td></tr><tr><td>4</td><td><strong>G</strong></td><td>到达目标，停止（或继续检查 F(f=8)=G(f=8) 是否有更优）</td><td>f(G)=8 最小且是目标</td></tr></tbody></table><p><strong>节点访问顺序：</strong>S → B → E → G</p><p><strong>找到路径：</strong>S → B → E → G，路径代价 = 3 + 1 + 4 = <strong>8</strong></p><p><strong>对比其他路径：</strong>S→A→C→G = 2+1+5=8（也是最优！），S→B→F→G = 3+4+2=9（次优），S→A→D→… 不可达 G。</p><h4>(3) 对比分析（3分）</h4><p>贪心 BFS 找到路径 S→B→F→G（代价 9），A* 找到路径 S→B→E→G（代价 8）。A* 更优。</p><p><strong>原因分析：</strong>从 B 扩展后，贪心只看 h 值——F(h=1) 比 E(h=2) 的启发式值更小，贪心立刻选择了「看起来更近」的 F。但 F 的 h 值虽然低，到达 F 的 g 值却是 7（S→B→F 已走了 7 步），而 E 虽然 h 稍大（h=2 vs h=1），但 g 只有 4（S→B→E 才走了 4 步）。A* 通过 f=g+h 计算：f(F)=7+1=8，f(E)=4+2=6——f(E) 更小，所以 A* 选择了 E。最终 S→B→E→G=8 < S→B→F→G=9，验证了 A* 的判断。</p><p><strong>f=g+h 的意义：</strong>g 是已经走过的路（沉没成本），h 是预估还要走的路。单独看 h 会被«看起来很美的捷径»欺骗——那条路可能很贵（g 很大）。只有 f=g+h 才能做全盘评估。</p><hr /><p><strong>评分要点：</strong></p><ul><li>贪心 BFS frontier 表正确 → 3分；路径及代价正确 → 2分</li><li>A* frontier 表正确（g/h/f 三个值完整）→ 5分；路径及代价正确 → 2分</li><li>对比分析：指出具体哪个节点的哪个值导致差异 + 解释 f 的意义 → 3分</li><li>易错点：G 在步骤 3 和 4 的 frontier 中出现了两次（经由 C 和 E），注意 g 值不同——经由 C 的 g=2+1+5=8，经由 E 的 g=3+1+4=8，代价值相同。如果经由 F，g=3+4+2=9。所以两条路径代价相同（都是 8），任选一条即可。</li></ul>"
  },
  {
    id: "sim-s2-3",
    moduleId: "s2",
    year: "模拟题",
    position: "自编",
    points: 8,
    questionText: "<p><strong>题型：分析题</strong> | <strong>参考分值：8分</strong></p><p><strong>题目：</strong>考虑以下搜索图（有向图，S 为起点，G 为目标）：</p><pre>    S\n   / \\\n (2) (5)\n  /     \\\n A       B\n  \\     /\n  (3) (1)\n    \\ /\n     G</pre><p>边代价如上标注。请回答：</p><p>(1) 计算每个节点到 G 的真实最小代价 h*(n)。（2分）</p><p>(2) 以下三个启发式函数，分别判断是否可采纳（admissible）、是否一致（consistent），并说明理由。（4分）</p><table><tbody><tr><th>节点</th><th>h₁(n)</th><th>h₂(n)</th><th>h₃(n)</th></tr><tr><td>S</td><td>4</td><td>6</td><td>5</td></tr><tr><td>A</td><td>3</td><td>4</td><td>2</td></tr><tr><td>B</td><td>1</td><td>1</td><td>2</td></tr><tr><td>G</td><td>0</td><td>0</td><td>0</td></tr></tbody></table><p>(3) 若分别使用 h₁、h₂、h₃ 作为 A* 的启发式函数，哪些能保证找到最优解？为什么？（2分）</p>",
    answerHtml: "<h4>(1) 真实代价 h*(n)（2分）</h4><p>从每个节点出发，到 G 的最小代价：</p><ul><li>h*(S) = min(2+3=5, 5+1=6) = <strong>5</strong>（S→A→G 的代价为 2+3=5）</li><li>h*(A) = <strong>3</strong>（A→G=3，唯一路径）</li><li>h*(B) = <strong>1</strong>（B→G=1，唯一路径）</li><li>h*(G) = <strong>0</strong>（已在目标）</li></ul><h4>(2) 启发式函数判定（4分）</h4><p><strong>h₁ —— 可采纳 ✓，一致 ✓</strong></p><p>可采纳性检查：h₁(S)=4 ≤ 5 ✓，h₁(A)=3 ≤ 3 ✓，h₁(B)=1 ≤ 1 ✓，h₁(G)=0 ≤ 0 ✓。全部满足 → 可采纳。</p><p>一致性检查（三角不等式 h(n) ≤ c(n,n') + h(n') 对所有边）：</p><ul><li>S→A: h₁(S)=4 ≤ c(S,A)+h₁(A)=2+3=5 ✓</li><li>S→B: h₁(S)=4 ≤ c(S,B)+h₁(B)=5+1=6 ✓</li><li>A→G: h₁(A)=3 ≤ c(A,G)+h₁(G)=3+0=3 ✓</li><li>B→G: h₁(B)=1 ≤ c(B,G)+h₁(G)=1+0=1 ✓</li></ul><p>全部满足 → 一致。</p><p><strong>h₂ —— 不可采纳 ✗，不一致 ✗</strong></p><p>可采纳性检查：h₂(S)=6 > 5=h*(S) ✗ —— S 节点的启发式值高估了真实代价，已违反可采纳性（此外 h₂(A)=4 > 3 ✗）。</p><p>一致性必然不满足（一致 → 可采纳的逆否命题：不可采纳 → 不一致）。直接验证 S→A：h₂(S)=6 > c(S,A)+h₂(A)=2+4=6？等号成立，但 S→B：h₂(S)=6 > c(S,B)+h₂(B)=5+1=6？等号。需看 A→G：h₂(A)=4 > c(A,G)+h₂(G)=3+0=3 ✗ → 不一致。</p><p><strong>h₃ —— 不可采纳 ✗，不一致 ✗</strong></p><p>可采纳性检查：h₃(B)=2 > 1=h*(B) ✗ —— B 节点高估。虽然 h₃(S)=5 ≤ 5 ✓、h₃(A)=2 ≤ 3 ✓，但只要有一个节点不满足可采纳性，整个启发式就是不可采纳的。</p><p>一致性检查：B→G: h₃(B)=2 > c(B,G)+h₃(G)=1+0=1 ✗ → 不一致。</p><h4>(3) A* 最优性保证（2分）</h4><p><strong>只有 h₁ 能保证 A* 找到最优解。</strong></p><p>h₁ 既可采纳又一致，无论是树搜索还是图搜索，A* 都保证最优。</p><p>h₂ 和 h₃ 都不可采纳——存在节点 n 满足 h(n) > h*(n)。高估意味着：A* 可能误判某个节点的 f 值偏高，将其排在 frontier 后面，导致最优路径上的节点被「跳过」。极端情况下，A* 可能完全错过最优解。</p><p><strong>核心结论（应作为答题要点）：</strong>可采纳性是 A* 最优性的必要前提——h 不能高估（overshoot）。一致性是更强的要求，额外保证了 f(n) 沿路径非递减（monotonic），使得 A* 在图搜索中第一次展开节点时就已找到最优路径。</p><hr /><p><strong>评分要点：</strong></p><ul><li>(1) h* 四个值全部正确 → 2分（错一个扣0.5分）</li><li>(2) 每个启发式的判断（可采纳/一致各 0.5分）+ 理由（0.5分）= 3×1.5 ≈ 4分。必须给出验证过程，不能只写结论。</li><li>(3) 正确指出 h₁ 可用、h₂/h₃ 不可用 → 1分；理由正确（提到高估/overshoot）→ 1分</li><li>常见扣分：只检查部分节点就下结论（必须检查所有节点）、混淆可采纳和一致的定义方向、把「h₃ 几乎对但一个节点错」当作可采纳</li></ul>"
  }
];