import type { ExamQuestion } from '@learncourse/framework/types';

export const S9_SIM_QUESTIONS: ExamQuestion[] = [
  {
    id: "sim-s9-1",
    moduleId: "s9",
    year: "模拟题",
    position: "自编",
    points: 10,
    questionText: "<p><strong>题目：</strong>某餐厅根据4个特征决定是否等待入座，收集了6条历史数据如下：</p><table><tbody><tr><th>编号</th><th>顾客人数</th><th>是否周末</th><th>是否饥饿</th><th>价格</th><th>等待？</th></tr><tr><td>1</td><td>少</td><td>否</td><td>是</td><td>普通</td><td>是</td></tr><tr><td>2</td><td>多</td><td>否</td><td>是</td><td>贵</td><td>否</td></tr><tr><td>3</td><td>多</td><td>是</td><td>是</td><td>普通</td><td>是</td></tr><tr><td>4</td><td>少</td><td>否</td><td>否</td><td>贵</td><td>否</td></tr><tr><td>5</td><td>少</td><td>是</td><td>是</td><td>普通</td><td>是</td></tr><tr><td>6</td><td>多</td><td>否</td><td>是</td><td>普通</td><td>否</td></tr></tbody></table><p>(1) 计算根节点的信息熵 H(D)（2分）<br>(2) 计算特征「是否周末」的信息增益 Gain(D, 是否周末)，并写出各子集的熵和条件熵（4分）<br>(3) 根据信息增益准则，应选择哪个特征作为根节点？简述信息增益在属性选择中的物理含义（4分）</p>",
    answerHtml: "<h4>(1) 根节点信息熵（2分）</h4>\n<p>数据集共6个样本，其中「是」=3个，「否」=3个。</p>\n<p>$H(D) = -\\frac{3}{6}\\log_2\\frac{3}{6} - \\frac{3}{6}\\log_2\\frac{3}{6} = -0.5 \\times (-1) - 0.5 \\times (-1) = \\mathbf{1.0}$</p>\n<p>熵为1.0说明数据集完全混乱——正负例各占一半，不确定性达到最大。</p>\n<h4>(2) 信息增益计算（4分）</h4>\n<p><strong>按「是否周末」划分：</strong></p>\n<table><tbody><tr><th>分组</th><th>样本编号</th><th>总数</th><th>是</th><th>否</th><th>熵</th></tr><tr><td>周末=是</td><td>3, 5</td><td>2</td><td>2</td><td>0</td><td>$H = -1\\log_2 1 - 0\\log_2 0 = \\mathbf{0}$（纯子集）</td></tr><tr><td>周末=否</td><td>1, 2, 4, 6</td><td>4</td><td>1</td><td>3</td><td>$H = -\\frac{1}{4}\\log_2\\frac{1}{4} - \\frac{3}{4}\\log_2\\frac{3}{4} = 0.25 \\times 2 + 0.75 \\times 0.415 = \\mathbf{0.811}$</td></tr></tbody></table>\n<p>$H(D|\\text{是否周末}) = \\frac{2}{6} \\times 0 + \\frac{4}{6} \\times 0.811 = 0 + 0.5407 = \\mathbf{0.541}$</p>\n<p>$\\text{Gain}(D, \\text{是否周末}) = H(D) - H(D|\\text{是否周末}) = 1.0 - 0.541 = \\mathbf{0.459}$</p>\n<p><strong>各特征信息增益完整对比：</strong></p>\n<table><tbody><tr><th>特征</th><th>H(D|特征)</th><th>Gain(D, 特征)</th></tr><tr><td>顾客人数</td><td>0.918</td><td>0.082</td></tr><tr><td><strong>是否周末</strong></td><td><strong>0.541</strong></td><td><strong>0.459</strong></td></tr><tr><td>是否饥饿</td><td>0.809</td><td>0.191</td></tr><tr><td><strong>价格</strong></td><td><strong>0.541</strong></td><td><strong>0.459</strong></td></tr></tbody></table>\n<h4>(3) 根节点选择与物理含义（4分）</h4>\n<p><strong>根节点选择：「是否周末」或「价格」均可——两者信息增益相同（0.459），并列最优。</strong>在ID3实际实现中，若两特征增益相同，通常按出现顺序选择第一个。</p>\n<p><strong>信息增益的物理含义：</strong>信息增益度量的是「知道特征A的值后，关于目标类别的信息量增加了多少」——即不确定性减少了多少。Gain = H(D) - H(D|A)，其中H(D)是划分前的不确定性，H(D|A)是划分后加权平均的不确定性。Gain越大，说明该特征对分类的「提纯」能力越强，越应该优先作为分裂节点。一言以蔽之：<strong>信息增益衡量特征A能为分类问题消除多少混乱。</strong></p>\n<p>以本题为例，Gain(是否周末)=0.459意味着知道「今天是否周末」后，关于「要不要等位」的不确定性从1.0降到了0.541，消除了约46%的不确定性——是四个特征中最有效的判别依据之一。</p>\n<hr /><p><strong>评分标准：</strong></p>\n<ul><li>(1) 公式正确 + 结果正确 = 2分；只写结果不写公式扣1分</li><li>(2) 每个子集统计正确各0.5分；各子集熵计算正确各0.5分；条件熵公式+结果1分；Gain结果1分</li><li>(3) 根节点选择正确1分；信息增益物理含义解释准确2分；能提到「不确定性减少」这一核心概念1分</li></ul>"
  },
  {
    id: "sim-s9-2",
    moduleId: "s9",
    year: "模拟题",
    position: "自编",
    points: 10,
    questionText: "<p><strong>题目：</strong>给定以下邮件训练数据，使用多项式朴素贝叶斯（Multinomial Naive Bayes）配合拉普拉斯平滑（\\alpha = 1）训练垃圾邮件分类器。</p><table><tbody><tr><th>编号</th><th>邮件内容（分词后）</th><th>类别</th></tr><tr><td>1</td><td>免费 领取 奖品 点击</td><td>垃圾</td></tr><tr><td>2</td><td>会议 通知 明天</td><td>正常</td></tr><tr><td>3</td><td>免费 优惠 点击 链接</td><td>垃圾</td></tr><tr><td>4</td><td>领取 会议 文件</td><td>正常</td></tr><tr><td>5</td><td>优惠 免费 领取</td><td>垃圾</td></tr></tbody></table><p>词汇表 V = [免费, 领取, 奖品, 点击, 会议, 通知, 明天, 优惠, 链接, 文件]，|V| = 10。</p><p>现有新邮件内容为「免费 领取 优惠」，请回答：<br>(1) 计算先验概率 P(垃圾) 和 P(正常)（1分）<br>(2) 写出拉普拉斯平滑后的似然概率公式，分别计算 P(免费|垃圾)、P(领取|垃圾)、P(优惠|垃圾) 和 P(免费|正常)、P(领取|正常)、P(优惠|正常)（4分）<br>(3) 计算后验概率并判断该邮件类别（3分）<br>(4) 简述「条件独立假设」在本题中的具体体现——为什么可以将三个单词的联合似然写为各自条件概率的乘积？如果实际语言中这些单词并非独立，为什么朴素贝叶斯通常仍表现良好？（2分）</p>",
    answerHtml: "<h4>(1) 先验概率（1分）</h4>\n<p>$P(\\text{垃圾}) = \\dfrac{3}{5} = 0.6$</p>\n<p>$P(\\text{正常}) = \\dfrac{2}{5} = 0.4$</p>\n<h4>(2) 拉普拉斯平滑后的似然概率（4分）</h4>\n<p><strong>拉普拉斯平滑公式：</strong>$P(w_i \\mid C) = \\dfrac{\\text{count}(w_i, C) + \\alpha}{\\text{total\\_words}_C + \\alpha \\cdot |V|}$，其中 $\\alpha = 1$。</p>\n<p><strong>各类别总词数：</strong>垃圾邮件共11个词（邮件1:4词 + 邮件3:4词 + 邮件5:3词）；正常邮件共6个词（邮件2:3词 + 邮件4:3词）。</p>\n<table><tbody><tr><th>单词</th><th>在垃圾中出现次数</th><th>$P(w|\\text{垃圾})$</th><th>在正常中出现次数</th><th>$P(w|\\text{正常})$</th></tr><tr><td>免费</td><td>3</td><td>$(3+1)/(11+10) = 4/21$</td><td>0</td><td>$(0+1)/(6+10) = 1/16$</td></tr><tr><td>领取</td><td>2</td><td>$(2+1)/(11+10) = 3/21$</td><td>1</td><td>$(1+1)/(6+10) = 2/16$</td></tr><tr><td>优惠</td><td>2</td><td>$(2+1)/(11+10) = 3/21$</td><td>0</td><td>$(0+1)/(6+10) = 1/16$</td></tr></tbody></table>\n<p><strong>注意：</strong>拉普拉斯平滑保证每个单词在任何类别中的条件概率都不为零——即使「免费」在正常邮件中出现次数为0，平滑后仍有 $P(\\text{免费}|\\text{正常}) = 1/16$，避免了「零概率」导致整个后验概率归零的问题。</p>\n<h4>(3) 后验概率与分类判断（3分）</h4>\n<p><strong>条件独立假设下：</strong>$P(\\text{新邮件}|C) = P(\\text{免费}|C) \\times P(\\text{领取}|C) \\times P(\\text{优惠}|C)$</p>\n<p>$P(\\text{新邮件}|\\text{垃圾}) = \\dfrac{4}{21} \\times \\dfrac{3}{21} \\times \\dfrac{3}{21} = \\dfrac{36}{9261}$</p>\n<p>$P(\\text{新邮件}|\\text{正常}) = \\dfrac{1}{16} \\times \\dfrac{2}{16} \\times \\dfrac{1}{16} = \\dfrac{2}{4096}$</p>\n<p><strong>后验比分（忽略归一化分母 P(新邮件)）：</strong></p>\n<p>$\\text{Score}(\\text{垃圾}) = P(\\text{垃圾}) \\times P(\\text{新邮件}|\\text{垃圾}) = 0.6 \\times \\dfrac{36}{9261} \\approx 0.00233$</p>\n<p>$\\text{Score}(\\text{正常}) = P(\\text{正常}) \\times P(\\text{新邮件}|\\text{正常}) = 0.4 \\times \\dfrac{2}{4096} \\approx 0.000195$</p>\n<p>$\\because \\text{Score}(\\text{垃圾}) > \\text{Score}(\\text{正常})$，$\\therefore$ 预测该邮件为<strong>垃圾邮件</strong>。</p>\n<p><strong>直观理解：</strong>新邮件中的三个词「免费」「领取」「优惠」在垃圾邮件中频繁出现（3次、2次、2次），在正常邮件中极少出现（0次、1次、0次），即使有先验概率和拉普拉斯平滑的调节，垃圾类别的综合得分仍远高于正常类别。</p>\n<h4>(4) 条件独立假设的含义与实践表现（2分）</h4>\n<p><strong>具体体现：</strong>在计算 $P(\\text{免费, 领取, 优惠} \\mid \\text{垃圾})$ 时，朴素贝叶斯将其分解为 $P(\\text{免费} \\mid \\text{垃圾}) \\times P(\\text{领取} \\mid \\text{垃圾}) \\times P(\\text{优惠} \\mid \\text{垃圾})$，即假设在已知邮件是垃圾的条件下，「免费」「领取」「优惠」这三个词的出现是彼此独立的。这忽略了词语间的共现关系——实际上垃圾邮件中「免费」和「领取」常同时出现，并非独立。</p>\n<p><strong>为什么实践中仍有效：</strong>虽然条件独立假设在绝大多数真实数据中不成立，但朴素贝叶斯关注的是 <strong>argmax</strong>（排序），而非精确的后验概率值。即使各概率估值有偏，只要 $P(\\text{垃圾} \\mid \\text{新邮件})$ 和 $P(\\text{正常} \\mid \\text{新邮件})$ 的相对大小关系正确，分类结果就不会出错。大量的实证研究表明，朴素贝叶斯在文本分类（特别是垃圾邮件过滤）中性能优异——这被称为「粗糙的概率估计，正确的分类决策」。</p>\n<hr /><p><strong>评分标准：</strong></p>\n<ul><li>(1) 两个先验概率各0.5分</li><li>(2) 拉普拉斯平滑公式写出1分；6个条件概率计算各0.5分（共3分）</li><li>(3) 联合似然分解式正确1分；两个Score计算正确各0.5分；最终判断正确1分</li><li>(4) 条件独立假设的解释1分；实践有效性解释1分</li></ul>"
  },
  {
    id: "sim-s9-3",
    moduleId: "s9",
    year: "模拟题",
    position: "自编",
    points: 10,
    questionText: "<p><strong>题目：</strong>给定一组二维数据点：(1, 2), (2, 3), (3, 5), (4, 6)。假设这些数据近似满足线性关系 y = wx + b。</p><p>(1) 写出最小二乘法（Least Squares）的优化目标函数（损失函数），并说明该函数为什么是凸函数（1分）<br>(2) 用最小二乘法求出最优参数 w 和 b（保留分数或小数形式）（5分）<br>(3) 计算模型在这些数据上的均方误差 MSE（2分）<br>(4) 用拟合的模型预测 x = 5 时的 y 值（2分）</p>",
    answerHtml: "<h4>(1) 优化目标函数（1分）</h4>\n<p>最小二乘法的优化目标是最小化残差平方和（Sum of Squared Residuals, SSR）：</p>\n<p>$J(w, b) = \\sum_{i=1}^{n} (y_i - \\hat{y}_i)^2 = \\sum_{i=1}^{n} (y_i - wx_i - b)^2$</p>\n<p>该函数是 <strong>w 和 b 的二次函数</strong>（展开后是 $w^2\\sum x_i^2 + 2wb\\sum x_i + nb^2 - 2w\\sum x_i y_i - 2b\\sum y_i + \\sum y_i^2$），Hessian 矩阵为正定矩阵（$\\sum x_i^2 > 0$ 且 $n > 0$），因此是严格凸函数——局部极小值即全局最小值，闭式解唯一。</p>\n<h4>(2) 参数求解（5分）</h4>\n<p><strong>计算样本均值：</strong></p>\n<p>$\\bar{x} = \\dfrac{1+2+3+4}{4} = 2.5$，$\\bar{y} = \\dfrac{2+3+5+6}{4} = 4.0$</p>\n<p><strong>计算 w（斜率）：</strong>$w = \\dfrac{\\sum(x_i - \\bar{x})(y_i - \\bar{y})}{\\sum(x_i - \\bar{x})^2}$</p>\n<table><tbody><tr><th>$i$</th><th>$x_i$</th><th>$y_i$</th><th>$x_i - \\bar{x}$</th><th>$y_i - \\bar{y}$</th><th>$(x_i - \\bar{x})(y_i - \\bar{y})$</th><th>$(x_i - \\bar{x})^2$</th></tr><tr><td>1</td><td>1</td><td>2</td><td>-1.5</td><td>-2.0</td><td>3.0</td><td>2.25</td></tr><tr><td>2</td><td>2</td><td>3</td><td>-0.5</td><td>-1.0</td><td>0.5</td><td>0.25</td></tr><tr><td>3</td><td>3</td><td>5</td><td>0.5</td><td>1.0</td><td>0.5</td><td>0.25</td></tr><tr><td>4</td><td>4</td><td>6</td><td>1.5</td><td>2.0</td><td>3.0</td><td>2.25</td></tr><tr><td colspan=3><strong>求和</strong></td><td>—</td><td>—</td><td><strong>7.0</strong></td><td><strong>5.0</strong></td></tr></tbody></table>\n<p>$w = \\dfrac{7.0}{5.0} = \\mathbf{1.4}$</p>\n<p><strong>计算 b（截距）：</strong></p>\n<p>$b = \\bar{y} - w\\bar{x} = 4.0 - 1.4 \\times 2.5 = 4.0 - 3.5 = \\mathbf{0.5}$</p>\n<p><strong>拟合模型：</strong>$\\hat{y} = 1.4x + 0.5$</p>\n<p><strong>验证：</strong>点1：$1.4\\times1+0.5=1.9$（实际2，残差0.1）；点2：$1.4\\times2+0.5=3.3$（实际3，残差-0.3）；点3：$1.4\\times3+0.5=4.7$（实际5，残差0.3）；点4：$1.4\\times4+0.5=6.1$（实际6，残差-0.1）。残差有正有负且大致对称，拟合良好。</p>\n<h4>(3) 均方误差 MSE（2分）</h4>\n<p>$\\text{MSE} = \\dfrac{1}{n}\\sum_{i=1}^{n}(y_i - \\hat{y}_i)^2 = \\dfrac{(2-1.9)^2 + (3-3.3)^2 + (5-4.7)^2 + (6-6.1)^2}{4}$</p>\n<p>$= \\dfrac{0.1^2 + (-0.3)^2 + 0.3^2 + (-0.1)^2}{4} = \\dfrac{0.01 + 0.09 + 0.09 + 0.01}{4} = \\dfrac{0.20}{4} = \\mathbf{0.05}$</p>\n<p>MSE = 0.05，非常小，说明线性模型对这四个数据点拟合得很好——数据本身接近一条直线。</p>\n<h4>(4) 预测（2分）</h4>\n<p>$\\hat{y}(5) = 1.4 \\times 5 + 0.5 = 7.0 + 0.5 = \\mathbf{7.5}$</p>\n<p><strong>注意：</strong>这是一个<strong>外推</strong>（extrapolation）预测——x=5 超出了训练数据范围 [1, 4]。线性模型假设数据的线性关系在训练范围外也成立，但实际中需谨慎：如果真实关系在 x 较大时偏离线性，预测误差可能显著增大。这也是线性模型的一个固有局限——模型的形式假设（线性）决定了其外推能力完全依赖于该假设的真实性。</p>\n<hr /><p><strong>评分标准：</strong></p>\n<ul><li>(1) 目标函数正确（残差平方和形式）0.5分；凸性解释0.5分</li><li>(2) $\\bar{x}$、$\\bar{y}$ 计算各0.5分（共1分）；协方差/方差计算表或直接公式1分；w计算正确2分；b计算正确1分</li><li>(3) MSE公式0.5分；四个残差各0.25分+MSE最终结果0.5分 = 2分</li><li>(4) 代入计算正确1分；提到外推局限性的额外给0.5分（奖励不超过满分10分）</li><li>若用正规方程（Normal Equation）$\\hat{\\beta} = (X^TX)^{-1}X^Ty$ 求解，过程正确同样得满分</li></ul>"
  }
];