import type { ExamQuestion } from '@learncourse/framework/types';

// ── 模拟题 ──
export const S8_SIM_QUESTIONS: ExamQuestion[] = [
  {
    id: "sim-s8-1",
    moduleId: "s8",
    year: "模拟题",
    position: "自编",
    points: 12,
    questionText: "<p><strong>题型：分析计算题</strong></p>\n<p>阅读以下C程序，假设所有fork()调用均成功，且各进程调度顺序不确定。</p>\n<pre>int main() {\n    int x = 0;\n    pid_t p1, p2;\n    p1 = fork();\n    if (p1 == 0) x += 1;\n    p2 = fork();\n    if (p2 == 0) x += 2;\n    if (p1 &gt; 0 &amp;&amp; p2 &gt; 0) x += 4;\n    printf(「x=%d\\n」, x);\n    return 0;\n}</pre>\n<p><strong>问题：</strong></p>\n<p>（1）请画出该程序创建的完整进程树，标注每个进程的父子关系以及最终输出的x值。（6分）</p>\n<p>（2）列出该程序所有可能的输出值（注意：不同进程的输出可能相同，也可能不同）。（6分）</p>",
    answerHtml: "<p><strong>参考答案：</strong></p>\n<p><strong>（1）进程树及x值推导</strong></p>\n<p>设初始进程为P0，x初始值为0。</p>\n<p><strong>第一步：p1 = fork()</strong><br>P0执行fork()后：P0中p1 &gt; 0（等于子进程PID），x=0，if(p1==0)条件不成立，跳过。<br>P1（P0的子进程）中p1 == 0，执行x += 1，x变为1。</p>\n<p><strong>第二步：p2 = fork()——P0和P1两个进程均执行此语句</strong><br>P0执行fork()：父路径p2 &gt; 0，x保持0；子进程P2中p2 == 0，执行x += 2，x变为2。<br>P1执行fork()：父路径p2 &gt; 0，x保持1；子进程P3中p2 == 0，执行x += 2，x变为3。</p>\n<p><strong>第三步：if(p1 &gt; 0 &amp;&amp; p2 &gt; 0) x += 4——仅当进程既是第一次fork的父(p1&gt;0)又是第二次fork的父(p2&gt;0)时执行</strong><br>P0：p1&gt;0且p2&gt;0均满足，x = 0 + 4 = 4，输出<strong>x=4</strong>。<br>P1：p1==0（是第一次fork的子进程），条件不满足，x保持1，输出<strong>x=1</strong>。<br>P2：p2==0（是P0执行第二次fork的子），条件不满足，x保持2，输出<strong>x=2</strong>。<br>P3：p1==0且p2==0，条件不满足，x保持3，输出<strong>x=3</strong>。</p>\n<p><strong>进程树（标注最终x值）：</strong></p>\n<pre>\n        P0 (x=4)\n       /      \\\n   P1 (x=1)  P2 (x=2)\n     |\n   P3 (x=3)\n</pre>\n<p>P0为原始进程；P1和P2是P0的直接子进程（分别来自p1=fork()和p2=fork()）；P3是P1的子进程（P1执行p2=fork()时产生）。共4个进程。</p>\n<p><strong>（2）所有可能的输出值</strong></p>\n<p>4个进程分别输出：<strong>x=1、x=2、x=3、x=4</strong>。共4种不同的数值。由于调度顺序不确定，输出行的排列顺序可以是任意组合（例如：x=1 / x=3 / x=2 / x=4 或 x=4 / x=1 / x=2 / x=3等），但值的集合固定为{1, 2, 3, 4}。每个进程恰好输出一行。</p>\n<p><strong>考点说明：</strong>本题考察fork()的核心语义——fork()在父进程中返回子进程PID(&gt;0)，在子进程中返回0；以及fork()后父子进程拥有独立的变量副本（COW语义下的逻辑等价）。需要逐层追踪每个进程的控制流和数据状态，不能遗漏任何分支路径。</p>"
  },
  {
    id: "sim-s8-2",
    moduleId: "s8",
    year: "模拟题",
    position: "自编",
    points: 10,
    questionText: "<p><strong>题型：简答题</strong></p>\n<p>某单核Linux系统上运行着两个用户进程A和B。进程A正在执行浮点密集计算（无系统调用），此时可编程间隔定时器（PIT）产生中断，内核决定调度进程B运行。</p>\n<p><strong>问题：</strong></p>\n<p>（1）请按时间顺序描述从定时器中断产生到进程B开始执行用户态代码的完整过程。内容包括：硬件自动完成的操作、内核执行的操作、以及涉及的关键数据结构。（6分）</p>\n<p>（2）如果进程B接下来也要执行浮点指令，内核在上下文切换时对浮点寄存器可以采用什么优化策略？说明该策略的基本原理及其优点。（4分）</p>",
    answerHtml: "<p><strong>参考答案：</strong></p>\n<p><strong>（1）从定时器中断到进程B执行的完整流程</strong></p>\n<p><strong>阶段一：硬件自动操作（中断响应）</strong><br>CPU完成当前指令后检测到INTR引脚上的中断信号，通过APIC获取中断向量号N。硬件自动完成以下操作：①将当前SS、RSP、RFLAGS、CS、RIP依次压入进程A的内核栈（每个8字节，共40字节）；②以向量号N为索引，从IDT（中断描述符表）的第N项加载新的CS和RIP（指向内核定时器中断处理入口）；③CPU特权级从Ring 3切换到Ring 0；④清除RFLAGS中的IF标志，禁止中断嵌套。</p>\n<p><strong>阶段二：内核保存进程A的上下文</strong><br>中断入口代码（汇编）在进程A的内核栈上继续压入剩余的通用寄存器（%rax、%rbx、%rcx、%rdx、%rsi、%rdi、%rbp、%r8~%r15）和段寄存器。这些信息后续存入进程A的task_struct（即PCB）的thread_struct字段中。内核更新A的状态为TASK_RUNNING（若仍可运行）或相应等待状态，并将其task_struct放回运行队列（runqueue）。</p>\n<p><strong>阶段三：调度决策</strong><br>中断处理尾声调用schedule()。调度器（CFS）从当前CPU的运行队列中选择vruntime最小的可运行进程——假设选中进程B。B的task_struct从队列中取出，状态设为TASK_RUNNING。调度器更新运行队列的curr指针指向B。</p>\n<p><strong>阶段四：切换地址空间</strong><br>内核执行switch_mm()：将CR3寄存器的值更新为进程B的页表基址（保存在B的mm_struct→pgd中）。如果CPU支持PCID/ASID，则加载B对应的ASID，避免不必要的TLB刷新——仅当ASID不匹配的TLB条目才失效。</p>\n<p><strong>阶段五：恢复进程B的上下文</strong><br>内核调用switch_to()，从进程B的内核栈/thread_struct中恢复其之前被保存的全部寄存器。最后通过iretq指令（或通过sysret路径）将SS、RSP、RFLAGS、CS、RIP从内核栈中弹出，CPU特权级从Ring 0回到Ring 3，进程B从其上次被中断的位置继续执行用户态代码。</p>\n<p><strong>关键数据结构：</strong>task_struct（包含进程状态state、thread_struct硬件上下文、mm_struct内存描述符、fs文件系统信息、sched_entity调度实体）、内核栈（每个进程拥有独立的内核栈，存储硬件上下文和内核函数调用链）、IDT（中断描述符表，256个门描述符，将中断向量映射到处理程序入口）、runqueue（每CPU的运行队列，CFS通过红黑树组织调度实体）。</p>\n<p><strong>（2）浮点寄存器的惰性保存/恢复策略</strong></p>\n<p><strong>策略名称：</strong>惰性FPU上下文切换（Lazy FPU Save/Restore），也称延迟FPU保存。</p>\n<p><strong>基本原理：</strong>在上下文切换时，内核并不立即保存进程A的浮点/向量寄存器（XMM/YMM/ZMM/ST/MMX）状态，也不恢复进程B的。而是将CR0寄存器的TS（Task Switched）标志置1。当进程B首次执行浮点指令时，TS标志触发#NM（Device Not Available）异常。内核在#NM异常处理中才执行实际的FPU状态操作：①如果FPU当前保存的是进程A的状态，则将其保存到A的task_struct；②从B的task_struct恢复B的FPU状态（如果B之前使用过浮点）或初始化干净的FPU状态（如果B首次使用浮点）；③清除TS标志。</p>\n<p><strong>优点：</strong>①如果进程B在本次时间片内未执行任何浮点指令（例如仅做整数计算、字符串处理或等待I/O），则完全避免了FPU上下文的保存和恢复开销——FPU状态可以继续属于进程A，下次切回A时无需任何FPU操作。②对于大量不使用浮点的进程（如shell、HTTP服务器、文本处理工具），该优化显著减少了上下文切换的平均开销。③现代CPU的FPU/SSE/AVX寄存器组非常庞大（AVX-512的ZMM寄存器可达2KB），惰性策略避免了对这些大寄存器的无效操作。</p>"
  },
  {
    id: "sim-s8-3",
    moduleId: "s8",
    year: "模拟题",
    position: "自编",
    points: 8,
    questionText: "<p><strong>题型：分析简答题</strong></p>\n<p>某网络服务器使用多进程模型：父进程监听端口，每accept()一个连接就fork()子进程处理。为避免僵尸进程，父进程注册了SIGCHLD信号处理函数：</p>\n<pre>void sigchld_handler(int sig) {\n    int status;\n    pid_t pid;\n    while ((pid = waitpid(-1, &amp;status, WNOHANG)) &gt; 0) {\n        /* 记录日志：子进程 pid 已回收 */\n    }\n}\n</pre>\n<p><strong>问题：</strong></p>\n<p>（1）信号处理函数中为什么使用while循环而非单次waitpid？WNOHANG选项在此场景下起什么作用？（3分）</p>\n<p>（2）标准信号（非实时信号）语义下，假设在sigchld_handler执行期间又有两个子进程同时终止，这两个终止事件会导致sigchld_handler被调用几次？是否存在子进程未被回收的风险？如何规避？（3分）</p>\n<p>（3）如果父进程在回收某些子进程之前就崩溃退出了，那些尚未回收的子进程会成为什么？内核如何处理它们？（2分）</p>",
    answerHtml: "<p><strong>参考答案：</strong></p>\n<p><strong>（1）while循环与WNOHANG的作用</strong></p>\n<p><strong>使用while循环的原因：</strong>SIGCHLD信号在标准信号语义下是<strong>不可靠的</strong>——多个子进程几乎同时终止时，多个SIGCHLD可能在内核中被合并为一次投递（信号不排队）。如果处理函数中只调用一次waitpid，当多个子进程已终止时，只会回收其中一个，其余保持僵尸状态。while循环持续调用waitpid，直到返回0（无更多已终止子进程），确保一次信号处理中回收<strong>所有</strong>已终止的子进程。</p>\n<p><strong>WNOHANG的作用：</strong>使waitpid非阻塞——如果当前没有已终止的子进程，立即返回0而不是挂起信号处理函数。这对信号处理函数至关重要：处理函数必须尽快返回以免阻塞整个进程的信号处理机制；同时它也防止了处理函数因等待未终止的子进程而永久挂起。</p>\n<p><strong>（2）信号合并与风险规避</strong></p>\n<p>在标准信号语义下，两个子进程同时终止最多导致sigchld_handler被调用<strong>1次</strong>（而非2次）。内核将SIGCHLD标记为待决（pending），但pending位图每个信号只有1位——多个同种信号只记录「有待决信号」这一事实。</p>\n<p><strong>潜在风险：</strong>虽然while循环缓解了「单次调用只能回收一个」的问题，但仍有竞态窗口：如果sigchld_handler执行while循环完毕（waitpid返回0）并即将返回时，又有一个子进程终止，内核会再次将SIGCHLD标记为pending。由于pending位已经存在（处理函数尚未返回），这个新终止可能被合并，导致不会再次触发处理函数调用，该子进程被遗漏。</p>\n<p><strong>规避方案：</strong>①父进程在处理请求的主循环中也周期性地调用waitpid(-1, &amp;status, WNOHANG)作为兜底，确保即使信号被漏掉也能回收；②使用sigaction()配合SA_NOCLDWAIT标志，让内核在子进程终止时自动回收，不产生僵尸进程也不发送SIGCHLD；③显式设置signal(SIGCHLD, SIG_IGN)，在Linux上会触发内核自动回收子进程（POSIX标准对此行为未明确定义，但Linux实现了）。</p>\n<p><strong>（3）父进程退出后子进程的归属</strong></p>\n<p>父进程退出后，其所有尚未终止的子进程变为<strong>孤儿进程（orphan process）</strong>。内核检测到子进程的父进程已退出后，将这些子进程的父进程ID（PPID）重新设置为<strong>1</strong>，即init进程（在现代Linux中通常是systemd）。子进程本身继续正常运行，不受父进程退出的直接影响。</p>\n<p>当孤儿进程最终终止时，其新父进程init会持续调用wait()/waitpid()来回收它们。因此孤儿进程不会永久成为僵尸进程——init进程是可靠的回收者。子进程已经终止但尚未被回收时父进程退出：这些已终止的僵尸子进程同样会被init收养并回收，其退出状态被丢弃（init不关心）。</p>"
  },
];