import type { ExamQuestion } from '@learncourse/framework/types';

// ── 模拟题 ──
export const S12_SIM_QUESTIONS: ExamQuestion[] = [
  {
    id: "sim-s12-1",
    moduleId: "s12",
    year: "模拟题",
    position: "计算题（自编）",
    points: 10,
    questionText: "<p><strong>题目：缓冲区溢出偏移量计算与 Payload 构造</strong></p><p>在 x86-32 Linux 平台上，以下程序以 root 权限编译运行，编译时未启用任何防御（无 Canary、无 NX、无 PIE）：</p><pre>#include &lt;stdio.h&gt;\n#include &lt;string.h&gt;\n\nvoid echo_wrapper(char *input) {\n    char buffer[100];\n    strcpy(buffer, input);\n    printf(\"Echo: %s\\n\", buffer);\n}\n\nint main(int argc, char *argv[]) {\n    if (argc &gt; 1)\n        echo_wrapper(argv[1]);\n    return 0;\n}</pre><p>已知 echo_wrapper 的汇编入口为：</p><pre>pushl   %ebp\nmovl    %esp, %ebp\nsub     $0x6c, %esp</pre><p>该函数未使用其他被调用者保存寄存器。</p><p><strong>请回答：</strong></p><p>(1) 画出栈帧布局，标出 buffer 起始位置、saved %ebp、返回地址的相对位置（以 %ebp 为基准），标注各区域大小。（3分）</p><p>(2) 攻击者要覆盖返回地址，需在 argv[1] 中至少填入多少字节？写出计算过程。（3分）</p><p>(3) 设 buffer 运行时地址为 0xbffff280，shellcode 长 45 字节。写出完整 Payload 结构，说明 shellcode 放哪、返回地址填什么值。（4分）</p>",
    answerHtml: "<p><strong>(1) 栈帧布局（3分）：</strong></p><p>sub $0x6c, %esp → 0x6C = 108 字节局部变量区。buffer[100] 占用其中 100 字节，起始于 %esp（即 %ebp - 0x6C = %ebp - 108）。剩余 8 字节为编译器插入的对齐填充（位于 buffer 上方、接近 %ebp 处）。</p><pre>高地址 ↑\n+-------------------------------+\n| 参数 input (argv[1] 指针)      |  ← %ebp + 8\n+-------------------------------+\n| 返回地址（4 字节）              |  ← %ebp + 4 ~ %ebp + 7\n+-------------------------------+\n| 旧 %ebp（4 字节）               |  ← %ebp ~ %ebp + 3\n+-------------------------------+\n| 对齐填充（8 字节）              |  ← %ebp - 12 ~ %ebp - 5\n|（编译器插入，实际可能与 buffer  |\n|  尾部有重叠，取决于分配策略）    |\n+-------------------------------+\n| buffer[96~99]                 |\n| ...                          |\n| buffer[0~3]                  |  ← %ebp - 108（= %esp）\n+-------------------------------+\n低地址 ↓</pre><p>简化：buffer[0] 在 %ebp-108 处，buffer[99] 在 %ebp-9 处。saved %ebp 在 %ebp~%ebp+3，返回地址在 %ebp+4~%ebp+7。</p><p><strong>评分要点：</strong>栈方向正确、%ebp 基准标注清晰（1分）；buffer 起始 %ebp-108 正确（1分）；saved %ebp 和返回地址位置正确（1分）。</p><p><strong>(2) 覆盖返回地址所需字节数（3分）：</strong></p><p>从 buffer[0]（%ebp-108）到返回地址末端的距离：</p><p>= 局部变量区 108 字节 + saved %ebp 4 字节 + 返回地址 4 字节</p><p>= 108 + 4 + 4 = <strong>116 字节</strong></p><p>其中：前 100 字节填满 buffer，接着 8 字节覆盖对齐填充区，再 4 字节覆盖 saved %ebp（可填任意值如 0x41414141），最后 4 字节覆盖返回地址为攻击者控制的值。</p><p><strong>答案：116 字节。</strong></p><p><strong>评分要点：</strong>正确识别 sub $0x6c = 108 字节局部区（1分）；+4(saved %ebp)+4(ret addr) 正确（1分）；最终结果 116 正确（1分）。</p><p><strong>(3) Payload 结构（4分）：</strong></p><p><strong>方案（shellcode 在 buffer 前端 + NOP sled）：</strong></p><pre>Payload = [45B shellcode] + [55B NOP(0x90)] + [8B 对齐区] + [4B 任意值(saved ebp)] + [4B 返回地址=0xbffff280]</pre><p>总长：45 + 55 + 8 + 4 + 4 = 116 字节。shellcode 放在 buffer 最开头，后面跟 55 字节 NOP sled（0x90）填满 buffer 到 100 字节，再 8 字节覆盖对齐区，4 字节覆盖 saved %ebp（任意），最后 4 字节返回地址填 0xbffff280（buffer 起始地址 = shellcode 起始地址）。NOP sled 的作用是增加容错率——即使返回地址有少量偏差（如 0xbffff284），CPU 也会「滑」过 NOP 指令到达 shellcode。</p><p><strong>替代方案（shellcode 在溢出区之后）：</strong>返回地址指向 shellcode 放置处（如 buffer 起始 + 116 偏移），Payload 更长但同样有效。</p><p><strong>评分要点：</strong>Payload 总字节数 116 正确（1分）；shellcode 放置位置合理（1分）；返回地址正确指向 shellcode（1分）；提到 NOP sled 的作用（1分）。</p>"
  },
  {
    id: "sim-s12-2",
    moduleId: "s12",
    year: "模拟题",
    position: "简答题（自编）",
    points: 8,
    questionText: "<p><strong>题目：三大防御机制的原理、局限性与纵深防御</strong></p><p>现代系统使用 Stack Canary、NX（DEP）和 ASLR 三种机制构成纵深防御来对抗缓冲区溢出攻击。</p><p><strong>请回答：</strong></p><p>(1) 分别用一句话简述每种防御的核心原理（每种不超过 40 字）。（3分）</p><p>(2) 若程序同时启用了三种防御，攻击者是否仍可能成功？如果能，请描述一种至少绕过其中两种防御的攻击路径。（3分）</p><p>(3) 为什么三种防御必须配合使用（纵深防御）？若只启用其中一种（如仅 Canary），存在什么风险？（2分）</p>",
    answerHtml: "<p><strong>(1) 三大防御核心原理（3分，每种1分）：</strong></p><p><strong>Stack Canary：</strong>编译器在返回地址前插入随机守卫值，函数返回前检查该值是否被篡改，若被修改则立即终止程序。</p><p><strong>NX / DEP：</strong>通过页表 NX 位标记栈和堆所在页面为不可执行，CPU 从这些页面取指令执行时触发硬件异常终止程序。</p><p><strong>ASLR：</strong>每次程序启动时随机化栈、堆、共享库等区域的基地址，使攻击者无法在代码中硬编码目标地址。</p><p><strong>评分要点：</strong>每种 1 分，必须写清「做什么」而非只写名称。关键：Canary=守卫值+返回前比对；NX=页表标志+禁止执行栈；ASLR=加载时随机化+隐藏地址。</p><p><strong>(2) 可绕过——信息泄露 + ROP 攻击路径（3分）：</strong></p><p>三步绕过三种防御：</p><p><strong>Step 1 — 绕过 ASLR（信息泄露）：</strong>利用程序的另一个漏洞（如格式化字符串 %x 泄露、越界读）读出栈或 libc 中的某个地址值，据此推算出 libc 基址和栈基址。</p><p><strong>Step 2 — 绕过 Canary（信息泄露）：</strong>如果同一漏洞还能读出金丝雀所在栈位置的值，攻击者获得金丝雀值，在构造溢出 Payload 时在对应偏移处填入正确的金丝雀值——函数返回时比对通过。</p><p><strong>Step 3 — 绕过 NX（ROP）：</strong>栈不可执行，不能注入 shellcode。转而使用 ROP（Return-Oriented Programming）：在 libc 等可执行代码段中寻找以 ret 结尾的短指令序列（gadget），串联多个 gadget 构造任意逻辑。例如通过 ROP 链调用 mprotect() 将栈改为可执行，然后执行 shellcode；或直接调用 system(\"/bin/sh\")。</p><p>完整链路：格式化字符串泄露地址+Canary → 栈溢出写入正确 Canary + ROP 链 → 函数返回时 Canary 验证通过 → 跳转到 ROP 链的第一个 gadget → 攻击成功。</p><p><strong>评分要点：</strong>信息泄露绕过 ASLR（1分）；读出并填入正确 Canary（0.5分）；ROP 绕过 NX（1分）；攻击链路清晰完整（0.5分）。</p><p><strong>(3) 纵深防御的必要性（2分）：</strong></p><p><strong>纵深防御</strong>意味着多层不同机制相互补充——一层被突破时下一层继续阻挡。三层覆盖三个攻击阶段：Canary 检测溢出是否发生；NX 阻止注入代码被执行；ASLR 让攻击者找不到目标。</p><p><strong>单层防御的风险：</strong>仅启用 Canary 时，攻击者可通过信息泄露获取守卫值后填入正确值绕过；绕过 Canary 后若无 NX，可注入 shellcode 直接执行；若无 ASLR，返回地址可硬编码。真实攻击中任何单一防御都可被针对性突破，必须多层配合才能形成有效防御。现代 CTF 比赛中许多利用链（exploit chain）恰恰是证明了单层防御的脆弱性——几乎所有成功的攻击都需要依次绕过多种防御。</p><p><strong>评分要点：</strong>解释纵深防御含义（1分）；给出单层防御的具体风险场景（1分）。</p>"
  },
  {
    id: "sim-s12-3",
    moduleId: "s12",
    year: "模拟题",
    position: "代码分析题（自编）",
    points: 6,
    questionText: "<p><strong>题目：不安全代码审计与修复</strong></p><p>以下 C 程序是用户登录模拟模块，存在多处安全隐患。请仔细阅读代码并回答问题。</p><pre>#include &lt;stdio.h&gt;\n#include &lt;string.h&gt;\n\n#define USERNAME_MAX 32\n#define PASSWORD_MAX 32\n\nstruct user {\n    char name[USERNAME_MAX];\n    char pass[PASSWORD_MAX];\n    int is_admin;\n};\n\nint check_login(char *user_input, char *pass_input) {\n    char log_buf[64];\n    struct user u;\n    u.is_admin = 0;\n    \n    strcpy(u.name, user_input);    /* ① */\n    strcpy(u.pass, pass_input);    /* ② */\n    \n    sprintf(log_buf, \"Login: user=%s\", u.name);  /* ③ */\n    printf(\"%s\\n\", log_buf);\n    \n    if (strcmp(u.name, \"admin\") == 0 &amp;&amp;   /* ④ */\n        strcmp(u.pass, \"s3cr3t\") == 0) {\n        u.is_admin = 1;\n    }\n    return u.is_admin;\n}\n\nint main() {\n    char username[256], password[256];\n    printf(\"Username: \");\n    gets(username);                 /* ⑤ */\n    printf(\"Password: \");\n    gets(password);                 /* ⑥ */\n    \n    if (check_login(username, password))\n        printf(\"Access granted.\\n\");\n    else\n        printf(\"Access denied.\\n\");\n    return 0;\n}</pre><p><strong>请回答：</strong></p><p>(1) 代码中标注了 ①~⑥ 共 6 处。逐项指出存在安全问题的位置，说明具体风险。（最多 4 分，每条 1 分）</p><p>(2) 对每处识别出的问题，写出使用安全函数或边界检查的修复方案。（2分）</p>",
    answerHtml: "<p><strong>(1) 安全隐患分析（最多 4 分，每条 1 分）：</strong></p><p><strong>① strcpy(u.name, user_input)：缓冲区溢出风险。</strong>u.name 仅 32 字节（USERNAME_MAX），但 user_input 来自 main 中 username[256]，最长可达 255 字符。若 user_input 超过 31 字符（留 1 字节给 '\\0'），则溢出覆盖 u.pass、u.is_admin 以及栈上的 saved %ebp 和返回地址。攻击者可通过超长用户名直接控制程序流或获取管理员权限（覆盖 is_admin 为 1）。</p><p><strong>② strcpy(u.pass, pass_input)：同①，同样存在溢出风险。</strong>超长密码输入同样可覆盖栈数据。</p><p><strong>③ sprintf(log_buf, \"Login: user=%s\", u.name)：二次溢出风险。</strong>log_buf 仅 64 字节。正常情况下 u.name 最多 31 字符 + 前缀 \"Login: user=\"（12 字符）= 43 字节，勉强安全。但如果 ① 先溢出 u.name 导致 '\\0' 被覆盖，u.name 变成无终止符的超长字符串，sprintf 的 %s 会一直读到碰巧遇到 '\\0' 为止，导致 log_buf 溢出。此外 sprintf 本身也不安全——应始终使用 snprintf。</p><p><strong>⑤ gets(username)：严重高危。</strong>gets() 不检查边界，可读入任意长度的数据到仅 256 字节的 username，直接溢出 main 的栈帧。这是整个程序最明显的漏洞。</p><p><strong>⑥ gets(password)：同⑤，同样严重。</strong></p><p><strong>④ strcmp 本身无直接溢出问题，</strong>但如果 u.name 或 u.pass 因 ①/② 溢出而丢失 '\\0'，strcmp 会越界读取，可能导致信息泄露或崩溃。</p><p><strong>评分要点：</strong>正确指出 ①/② 溢出风险（合计 1 分）；正确指出 ③ 的二次溢出/连锁风险（1 分）；正确指出 ⑤/⑥ gets 风险（1 分）；额外识别逻辑缺陷或连锁效应（1 分）。</p><p><strong>(2) 修复方案（2分）：</strong></p><table><tbody><tr><th>位置</th><th>原代码</th><th>修复方案</th></tr><tr><td>①</td><td>strcpy(u.name, user_input)</td><td>strncpy(u.name, user_input, USERNAME_MAX - 1); u.name[USERNAME_MAX - 1] = '\\0';</td></tr><tr><td>②</td><td>strcpy(u.pass, pass_input)</td><td>strncpy(u.pass, pass_input, PASSWORD_MAX - 1); u.pass[PASSWORD_MAX - 1] = '\\0';</td></tr><tr><td>③</td><td>sprintf(log_buf, \"Login: user=%s\", u.name)</td><td>snprintf(log_buf, sizeof(log_buf), \"Login: user=%.31s\", u.name);</td></tr><tr><td>⑤</td><td>gets(username)</td><td>fgets(username, sizeof(username), stdin); username[strcspn(username, \"\\n\")] = '\\0';</td></tr><tr><td>⑥</td><td>gets(password)</td><td>fgets(password, sizeof(password), stdin); password[strcspn(password, \"\\n\")] = '\\0';</td></tr></tbody></table><p><strong>不安全函数及其安全替代：</strong>gets→fgets（限制长度）；strcpy→strncpy（手动补'\\0'）；strcat→strncat；sprintf→snprintf；scanf(\"%s\")→scanf(\"%Ns\")。注意 strncpy 的陷阱：若 src 长度 >= n，dst 不会以 '\\0' 结尾，必须手动置 '\\0'。</p><p><strong>评分要点：</strong>①② 修复正确（0.5 分）；③ 修复正确（0.5 分）；⑤⑥ 修复正确并处理换行符（0.5 分）；提到 strncpy '\\0' 陷阱或给出完整对照表（0.5 分）。</p>"
  }
];